# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfui" do
  version "0.3.3"

  on_macos do
    on_intel do
      sha256 "9bf080adcdcb0bdf39d22da86633e3c3fc35ec87db5e198f39decd759dab94a3"
      url "https://github.com/SayYoungMan/tfui/releases/download/v#{version}/tfui_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3d47b41504d76d70d2bc2d2f70d93b7741a47b4a228c0d66be39a8dd4fd9c76f"
      url "https://github.com/SayYoungMan/tfui/releases/download/v#{version}/tfui_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "86a1e7fd051aca3c8e8cb30c8b07d79de9a379d29d187e587ff8ef3242896944"
      url "https://github.com/SayYoungMan/tfui/releases/download/v#{version}/tfui_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "444dde518200f40d3f5572a09f685d68322d9dfdc5d31f19b8450d8312a17ee8"
      url "https://github.com/SayYoungMan/tfui/releases/download/v#{version}/tfui_linux_arm64.tar.gz"
    end
  end

  name "tfui"
  desc "Interactive terminal UI for Terraform plan/apply workflows"
  homepage "https://github.com/SayYoungMan/tfui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfui"

  # No zap stanza required

end
