# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfui" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "7c7ed0768f913f0b067c0fabae11c3d8d96fdf293da2e9b3824158103a7da348"
      url "https://github.com/SayYoungMan/tfui/releases/download/v#{version}/tfui_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7781edc2107feeb99f08c66799b8411c4e5565f8f419381dd71088cbfa709868"
      url "https://github.com/SayYoungMan/tfui/releases/download/v#{version}/tfui_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3aef74ac63586ac476d165af041c7b4e4679ab9559e6fb3d87195dcc434d0890"
      url "https://github.com/SayYoungMan/tfui/releases/download/v#{version}/tfui_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5e83aa40302a399f7bcf72f1fe84a91ea319f0a8493e3699d6d77dabb1e96c28"
      url "https://github.com/SayYoungMan/tfui/releases/download/v#{version}/tfui_linux_arm64.tar.gz"
    end
  end

  name "tfui"
  desc "Interactive terminal UI for Terraform plan/apply workflows"
  homepage "https://github.com/SayYoungMan/tfui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfui"

  # No zap stanza required

end
