# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfui" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "98eee5091cf7870d8b0be743acfb81f7342af6b99c9e8f978b3f2b2e117b0f39"
      url "https://github.com/SayYoungMan/tfui/releases/download/v#{version}/tfui_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f9ed0e2d45f5c4d68dce94e2f79368afe697f51387a0a98a8c3a8fd0e0df1bc0"
      url "https://github.com/SayYoungMan/tfui/releases/download/v#{version}/tfui_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "376bcf9f04c87e5f4838467060b868d9d27fc68d273ffc2118ab287bfe35b7dd"
      url "https://github.com/SayYoungMan/tfui/releases/download/v#{version}/tfui_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1caf2b9dfd82449a3748742d504d1b1f5f79247990a8986d2df48891f0663eb2"
      url "https://github.com/SayYoungMan/tfui/releases/download/v#{version}/tfui_linux_arm64.tar.gz"
    end
  end

  name "tfui"
  desc "Interactive terminal UI for Terraform plan/apply workflows"
  homepage "https://github.com/SayYoungMan/tfui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfui"

  # No zap stanza required

end
